name: build
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: "ghcr.io/${{ github.repository }}:latest"
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          docker pull "$IMAGE"
          docker build --cache-from "$IMAGE" -t build-image .
      - name: Push to Docker Hub
        if: "github.repository == 'ustclug/light-server'"
        run: |
          docker login -u "${{ github.actor }}" -p "${{ github.token }}" ghcr.io
          docker push "$IMAGE"
